18 feature create tabtsx component
mlatsjsu/mlatsjsu-website pull request #63
Opened 2024-10-17 05:54 UTC by edwaddle

Unsure if this how you want it to be formatted

2024-12-04 06:07 UTC, ahmadgaz requested changes
awesome, just make sure to see the comment i made on error.tsx.

2024-12-04 06:07 UTC, ahmadgaz commented on app/error.tsx
This file is unrelated, make sure to pull dev and `git checkout <source-branch> -- <path/to/file>` to reset the file so that it isn't included in the PR.

2024-12-04 06:07 UTC, ahmadgaz commented on app/error.tsx
Make sure this file is unchanged in the last commit

2025-02-26 02:11 UTC, ahmadgaz requested changes
remove error.tsx fiile

2025-02-26 02:27 UTC, edwaddle commented
Not sure why it's not showing that I committed, but only 3 of the files are changed now

2025-02-26 03:03 UTC, ahmadgaz approved these changes

2025-02-27 05:23 UTC, merged